### ISSUE TITLE
Unable to connect public Github repo

### ISSUE THREAD

**Issue by johnd0e** [motifland/markprompt-js#179]
**Describe the bug**

"Connect GitHub repo" does not work for me.

**To Reproduce**

1. I copy and paste repo url and branch name
2. Click on Connect
3. Click on Train
4. See error "Error processing repo ... Make sure that main or master branch accessible ..."

**Comment by johnd0e** [comment]
https://github.com/FarManagerLegacy/macro-api
master

**Comment by michaelfester** [comment]
Hi @johnd0e, I was no able to reproduce there error, could you please try again and let us know if you still see it?

In any case, your repository does not seem to contain any Markdown or other supported files. We currently support `.md`, `.mdoc`, `.mdx`, `.rst`, `.html`, `.htm` and `.txt`.

**Comment by johnd0e** [comment]
1. Actually I've also tried a branch that contain .html files - gh-pages - without any luck either.
2. I would prefer to see more meaningful error message in case of no supported files found.
3. It could be convenient if you let more file extensions to be processed.

P.S.
My .text files are in fact markdown, but there is a reason not to have .md extension: there are a lot of flavors of markdown, and I use those .text as source for converting to different types, including github-flavored .md, as well as plain .txt.

**Comment by michaelfester** [comment]
I agree we should provide a more useful error message.

I was not able to reproduce your issue with the gh-pages branch, it seems to be processing the html file correctly on my end. So I wonder: do you have a custom [include/exclusion path configuration](https://markprompt.com/docs#configuration) by any chance?

I just pushed support for `.text` file extensions, which are treated as plain text files, so hopefully you should be able to get it working on the `master` branch.

**Comment by johnd0e** [comment]
> So I wonder: do you have a custom [include/exclusion path configuration](https://markprompt.com/docs#configuration) by any chance?

Right now I have tried to do this with new just created project, without any configuration.
And it still fails.

**Comment by michaelfester** [comment]
Thanks a lot. I think I found the culprit, and pushed a fix: https://github.com/motifland/markprompt/issues/184
